image: python:3.9

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install -r requirements-dev.txt -r requirements.txt

test:
  stage: test
  script:
    - pytest --nbval --sanitize-with sanitize.cfg --junit-xml=rspec.xml *.ipynb
  artifacts:
    reports:
      junit: rspec.xml

pages:
  stage: deploy
  script:
    - nbpretty .
    - for svg in *.svg; do scour "${svg}" "${svg}.out"; mv -f "${svg}.out" "${svg}"; done
    - mkdir -p public
    - cp *.{html,png,jpg,css,txt,csv} public/ || true
  artifacts:
    paths:
    - public
  only:
  - master
