name: Deploy Course

on:
  push:
    branches:
      - environmental-workshop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt -r requirements.txt

      # - name: Test
      #   run: |
      #     pytest --nbval --sanitize-with sanitize.cfg --junit-xml=rspec.xml *.ipynb
      

      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test output
      #     path: rspec.xml
      
      - name: Build a folder called public
        run: |
          nbpretty .
          for svg in *.svg; do scour "${svg}" "${svg}.out"; mv -f "${svg}.out" "${svg}"; done
          mkdir -p public
          cp *.{html,png,jpg,css,txt,csv,svg} public/ || true


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESSTOKEN }}
          publish_dir: ./public


      # - name: Init new repo in public folder and commit generated files
      #   run: |
      #     cd public/
      #     git init
      #     git add -A
      #     git config --local user.email ${{ secrets.GITHUBEMAIL }}
      #     git config --local user.name ${{ secrets.USERNAME }}
      #     git commit -m 'deploy'

      # - name: Force push to destination branch
      #   uses: ad-m/github-push-action@master
      #   with:
      #     # Token for the repo
      #     # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
      #     github_token: ${{ secrets.ACCESSTOKEN }}
      #     # Destination branch to push changes
      #     branch: gh-pages
      #     # Force the changes through
      #     force: true
      #     # Change to the build directory before pushing
      #     directory: public
      #     repository: "JGIBristol/environmental-data-analysis-in-python"
        